invitatioin_list=["陈哲远",'赵露思','毛不易','我自己']
len(invitatioin_list)
print(len(invitatioin_list))
print(invitatioin_list)
unable_to_attend='毛不易'
invitatioin_list.remove(unable_to_attend)
print(unable_to_attend)
print(f"\nDue to time schedule, {unable_to_attend} is unable to attend.")
invitatioin_list.insert(2,"李雪琴")
print(f"\nA new invitation list is {invitatioin_list}")
print(f'\nI find a new venu so i can invite more guest other than {invitatioin_list}')
invitatioin_list.insert(0,"王安宇")
invitatioin_list.insert(3,"秦岚")
invitatioin_list.append("小胡")
print(f"\n请嘉宾{invitatioin_list}参见我们的综艺")
print("因为weather，我只能邀请两个嘉宾")
poped_guest=invitatioin_list.pop()
print(f'\n对不清，由于经费无法邀请{poped_guest},请您见谅')
poped_guest=invitatioin_list.pop()
print(f'\n对不清，由于经费无法邀请{poped_guest},请您见谅')
poped_guest=invitatioin_list.pop()
print(f'\n对不清，由于经费无法邀请{poped_guest},请您见谅')
poped_guest=invitatioin_list.pop()
print(f'\n对不清，由于经费无法邀请{poped_guest},请您见谅')
poped_guest=invitatioin_list.pop()
print(f'\n对不清，由于经费无法邀请{poped_guest},请您见谅')
print(f"\n恭喜{invitatioin_list[0]},您还在邀请内")
print(f"\n恭喜{invitatioin_list[1]},您还在邀请内")
del invitatioin_list[0]
del invitatioin_list[0]
print(invitatioin_list)